/**
 * EcoStamp Phase 4 -- /api/signing-key
 *
 * Called by AdminPanel after approving a provider.
 * Delivers the signing key hash to the provider via email (stubbed)
 * and records the delivery in-memory (Phase 5: database).
 *
 * POST { providerId, keyHash, txid?, resend? }
 *   -> 200 { ok: true, delivered: true }
 *
 * In production this would:
 *   1. Look up the provider's contact email from a DB
 *   2. Send an encrypted email with the full secp256k1 private key
 *      (not just the hash -- the hash is what goes on-chain)
 *   3. Log the delivery event with timestamp + admin wallet
 *
 * The private key is generated by the admin off-band (or via a KMS),
 * and only the keccak256(pubkey) hash is stored on-chain in
 * provider-registry.clar (signing-key-hash field).
 */

import { NextRequest, NextResponse } from 'next/server';

// In-memory delivery log (Phase 5: replace with DB)
const deliveryLog: Array<{
  providerId: number;
  keyHash:    string;
  txid?:      string;
  deliveredAt: string;
  resend:     boolean;
}> = [];

export async function POST(req: NextRequest) {
  try {
    const { providerId, keyHash, txid, resend = false } = await req.json();

    if (!providerId || !keyHash) {
      return NextResponse.json({ error: 'providerId and keyHash required' }, { status: 400 });
    }

    // Validate keyHash is a plausible 32-byte hex
    const clean = String(keyHash).replace('0x', '');
    if (clean.length < 40 || !/^[0-9a-fA-F]+$/.test(clean)) {
      return NextResponse.json({ error: 'invalid keyHash format' }, { status: 400 });
    }

    // Record delivery
    const record = {
      providerId: Number(providerId),
      keyHash:    keyHash,
      txid:       txid ?? null,
      deliveredAt: new Date().toISOString(),
      resend,
    };
    deliveryLog.push(record);

    // --- Phase 5: email delivery stub ---
    // In production, trigger a transactional email here:
    //
    // await sendEmail({
    //   to:      providerEmail,
    //   subject: 'Your EcoStamp signing key is ready',
    //   body:    `Provider ID: ${providerId}\nKey hash (on-chain): ${keyHash}\n
    //             Your private signing key (keep secret):\n${privateKey}\n\n
    //             Approval tx: https://explorer.hiro.so/txid/${txid}?chain=testnet`,
    // });
    //
    // For now: log to server console as confirmation
    console.log('[signing-key] delivered', record);

    return NextResponse.json({ ok: true, delivered: true, record });
  } catch (e: any) {
    console.error('[signing-key] error', e);
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}

// GET /api/signing-key?providerId=X -- admin-only delivery log query
export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get('providerId');
  const records = id
    ? deliveryLog.filter(r => r.providerId === Number(id))
    : deliveryLog;
  return NextResponse.json({ records });
}